- hosts: all
  vars:
    var1:
    var2:
    var3:
    var4:
  tasks:
  - name: file
    win_template:
      src: build_config_template.j2
      dest: C:\build_config.txt
  - name: reboot
    win_reboot:
  - name: ping
    win_ping:
