- hosts: all
  vars:
    var1:
    var2:
    var3:
    var4:
    var5:
    var6:
  tasks:
  - name: file
    win_template:
      src: deploy_config_template.j2
      dest: C:\deploy_config.txt
  - name: reboot
    win_reboot:
  - name: ping
    win_ping:
