parameters:
  vm_image_name: ''
  vm_image_rg_name: ''
  vm_image_build_rg_name: ''
  ansible_playbook_path: ''
  ansible_extra_vars: ''

steps:
- checkout: self
  clean: true
  persistCredentials: false
  submodules: false

- task: AzureCLI@1
  condition: succeeded()
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      if [[ $(az group exists --name '${{ parameters.vm_image_build_rg_name }}') == *'true'* ]]; then {
        echo "ERROR: Resource group already exists, breaking.."
        exit 1
      } else {
        echo "Creating Resource group.."
        az group create --name '${{ parameters.vm_image_build_rg_name }}' --location '$(prodVmRegion)'
      }
      fi
    failOnStandardError: true
  name: 'create_rg'
  displayName: 'Create Resource group'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az vm create \
      --resource-group '${{ parameters.vm_image_build_rg_name }}' \
      --name '${{ parameters.vm_image_name }}' \
      --image 'Win2016Datacenter' \
      --location '$(prodVmRegion)' \
      --size '$(prodVm1Size)' \
      --subnet '/subscriptions/$(azureSubscriptionId)/resourceGroups/$(packerVnetResourceGroupName)/providers/Microsoft.Network/virtualNetworks/$(packerVnetName)/subnets/$(packerVnetSubnetName)' \
      --public-ip-address '' \
      --admin-username '$(ansibleUser)' \
      --admin-password '$(ansibleUserPass)' \
      --tags 'project=$(project)' 'environment=$(environment)'
    failOnStandardError: true
  name: 'create_vm'
  displayName: 'Create VM'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      VM_IP=$(az vm list-ip-addresses --resource-group ${{ parameters.vm_image_build_rg_name }} --name ${{ parameters.vm_image_name }} --query "[].virtualMachine.network.privateIpAddresses[]" --output tsv)
      echo "##vso[task.setvariable variable=VM_IP;isOutput=true]$VM_IP"
    failOnStandardError: true
  name: 'get_vm_ip'
  displayName: 'Get VM IP'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az vm run-command invoke --command-id RunPowerShellScript --resource-group ${{ parameters.vm_image_build_rg_name }} --name ${{ parameters.vm_image_name }} --scripts 'Invoke-WebRequest https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile ConfigureRemotingForAnsible.ps1; powershell.exe -ExecutionPolicy ByPass -File ./ConfigureRemotingForAnsible.ps1; Remove-Item ./ConfigureRemotingForAnsible.ps1'
    failOnStandardError: true
  name: 'setup_winrm'
  displayName: 'Setup WinRM'

- bash: |
    if [ -z "$GET_VM_IP_VM_IP" ]; then {
      echo "ERROR: GET_VM_IP_VM_IP variable is empty, breaking.."
      exit 1
    } else {
      echo "Creating hosts file.."
      echo -e "[all]\n$GET_VM_IP_VM_IP" > hosts
    }
    fi
  name: 'create_ansible_hosts'
  displayName: 'Create Ansible hosts file'

- bash: >
    ansible-playbook
    -vvvv
    -i hosts
    ${{ parameters.ansible_playbook_path }}
    --extra-vars='${{ parameters.ansible_extra_vars }}'
  name: 'execute_ansible'
  displayName: 'Execute Ansible provisioner'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az vm run-command invoke --command-id RunPowerShellScript --resource-group ${{ parameters.vm_image_build_rg_name }} --name ${{ parameters.vm_image_name }} --scripts '& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit'
      az vm deallocate --resource-group ${{ parameters.vm_image_build_rg_name }} --name ${{ parameters.vm_image_name }}
      az vm generalize --resource-group ${{ parameters.vm_image_build_rg_name }} --name ${{ parameters.vm_image_name }}
    failOnStandardError: true
  name: 'capture_preparation'
  displayName: 'Prepare for Caption'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      if [[ $(az image list --resource-group 'packer-images-rg' | jq --raw-output '.[] | .name') == *${{ parameters.vm_image_name }}* ]]; then {
        echo "Old image detected, deleting.."
        az image delete --resource-group ${{vm_image_rg_name}} --name ${{ parameters.vm_image_name }}
      } else {
        echo "Old image was not detected.."
      }
      fi
      echo "Creating image.."
      az image create --resource-group ${{vm_image_rg_name}} --name ${{ parameters.vm_image_name }} --source '/subscriptions/$(azureSubscriptionId)/resourceGroups/${{ parameters.vm_image_build_rg_name }}/providers/Microsoft.Compute/virtualMachines/${{ parameters.vm_image_name }}'
    failOnStandardError: true
  name: 'capture_image'
  displayName: 'Capture image'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az group delete --name ${{ parameters.vm_image_build_rg_name }} --yes
    failOnStandardError: true
  name: 'delete_rg'
  displayName: 'Delete Resource group'
